In [2]:
import pandas as pd

In [5]:
mylist = []
size = int(input("Enter size of data: "))
for x in range(0,size):
    value = int(input("Enter data: "))
    mylist.insert(x,value)
df = pd.DataFrame(mylist,columns=['X'])

Enter size of data: 3
Enter data: 1
Enter data: 2
Enter data: 3

In [13]:
def finddistance(c,enterlist,size):
    x = []
    for i in range(0,size):
        x.insert(i,abs(int(enterlist[i] - c)))
    return x
def condition(a,b):
    if a > b:
        return 'g'
    elif a < b:
        return 'l'
    elif a == b:
        return 'e'
import random
column = 'A'
previous = []
check2 = []
con = False
c1list = []
c2list = []
c1 = random.choice(mylist)
c2 = random.choice(mylist)

c1list = finddistance(c1,mylist,size)
c2list = finddistance(c2,mylist,size)

for i in range(0,size):
    if condition(c1list[i],c2list[i]) == 'g':
        check2.insert(i,'1')
    elif condition(c1list[i],c2list[i]) == 'l':
        check2.insert(i,'2')
    elif condition(c1list[i],c2list[i]) == 'e':
        check2.insert(i,'3')

previous = check2
df['C' + column + str(1)] = c1list
df['C' + column + str(2)] = c2list
column = chr(ord(column) + 1)

while True:
    c1list = []
    c2list = []
    c1 = random.choice(mylist)
    c2 = random.choice(mylist)
    c1list = finddistance(c1,mylist,size)
    c2list = finddistance(c2,mylist,size)
    check2 = []
    for i in range(0,size):
        if condition(c1list[i],c2list[i]) == 'g':
            check2.insert(i,'1')
        elif condition(c1list[i],c2list[i]) == 'l':
            check2.insert(i,'2')
        elif condition(c1list[i],c2list[i]) == 'e':
            check2.insert(i,'3')

    con = False

    for j in range(0,size):
        if previous[j] == '1' and check2[j] == '2':
            con = False
            break
        elif previous[j] == '2' and check2[j] == '1':
            con = False
            break
        elif previous[j] == '3' and check2[j] == '3':
            con = True
            break
        elif previous[j] == '3' and check2[j] == '2':
            con = True
            break
        elif previous[j] == '2' and check2[j] == '3':
            con = True
            break
        elif previous[j] == '3' and check2[j] == '1':
            con = True
            break
        elif previous[j] == '1' and check2[j] == '3':
            con = True
            break
        elif previous[j] == check2[j]:
            con = True

    df['C' + column + str(1)] = c1list
    df['C' + column + str(2)] = c2list
    column = chr(ord(column) + 1)
    if column == 'Z':
        column = 'A'
    if con == True:
        break
    pervious = check2

In [14]:
df

   X  CA1  CA2  CB1  CB2  CC1  CC2  CD1  CD2
0  1    0    1    1    2    1    2    0    2
1  2    1    0    0    1    0    1    1    1
2  3    2    1    1    0    1    0    2    0